name: dairy_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  palette_generator: ^0.3.3+5
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.1.2
  logger: ^2.5.0
  get_it: ^8.0.3
  flutter_bloc: ^9.0.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.1.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  awesome_dialog: ^3.0.2
  flutter_launcher_icons: ^0.14.2
  flutter_offline: ^4.0.0
  floor: ^1.4.2
  floor_generator: ^1.4.2
  intl: ^0.20.1
  fluttertoast: ^8.2.2
  mockito: ^5.4.0
  faker: ^2.1.0
  flutter_spinkit: ^5.2.0
  internet_connection_checker_plus: ^2.7.0
  connectivity_plus: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.1.2


flutter:

  uses-material-design: true
  assets:
    - assets/images/


flutter_icons:
  ios: true
  android: true
  image_path: assets/images/emt.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
